# Generated by Django 2.0.7 on 2018-08-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('namedrawing', '0002_auto_20180807_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
    ]
