# Generated by Django 2.0.7 on 2018-08-08 23:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namedrawing', '0003_remove_friendship_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='eligible_picks',
            field=models.ManyToManyField(related_name='eligible_picks', through='namedrawing.Friendship', to=settings.AUTH_USER_MODEL),
        ),
    ]
